import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {createRoot} from "react-dom/client"
import { Suspense } from 'react'
import { Loader } from '@react-three/drei'
import { cn } from '../../lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '3D Saul CV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"antialiased w-screen h-screen")}>{children}</body>
    </html>
  )
}
